// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBcmxt4yjfKbVw6c5HInFtevolu1LLqkg',
    appId: '1:133988075968:web:68120161b94b30f8a9e025',
    messagingSenderId: '133988075968',
    projectId: 'hw13-15',
    authDomain: 'hw13-15.firebaseapp.com',
    storageBucket: 'hw13-15.firebasestorage.app',
    measurementId: 'G-MN5XJ0T9NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZqAuAQDrt2nhpUU_J_TWHjir7y_CfdyU',
    appId: '1:133988075968:android:7bfc9f68f7f78007a9e025',
    messagingSenderId: '133988075968',
    projectId: 'hw13-15',
    storageBucket: 'hw13-15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVC9TPGHRiiWCfEZLUF8UH6N2xvGwzBdw',
    appId: '1:133988075968:ios:ada7b63cf1c53e7aa9e025',
    messagingSenderId: '133988075968',
    projectId: 'hw13-15',
    storageBucket: 'hw13-15.firebasestorage.app',
    iosBundleId: 'com.example.hw1315',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVC9TPGHRiiWCfEZLUF8UH6N2xvGwzBdw',
    appId: '1:133988075968:ios:ada7b63cf1c53e7aa9e025',
    messagingSenderId: '133988075968',
    projectId: 'hw13-15',
    storageBucket: 'hw13-15.firebasestorage.app',
    iosBundleId: 'com.example.hw1315',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBcmxt4yjfKbVw6c5HInFtevolu1LLqkg',
    appId: '1:133988075968:web:c5e4150c3240814ea9e025',
    messagingSenderId: '133988075968',
    projectId: 'hw13-15',
    authDomain: 'hw13-15.firebaseapp.com',
    storageBucket: 'hw13-15.firebasestorage.app',
    measurementId: 'G-GBVF00HN0Q',
  );

}