// Template for Firebase options - copy to firebase_options.dart and configure
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To configure:
/// 1. Run: flutterfire configure
/// 2. Or manually replace the values below with your Firebase project config
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Configure your Firebase project settings
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your_web_api_key_here',
    appId: 'your_web_app_id_here',
    messagingSenderId: 'your_sender_id_here',
    projectId: 'your_project_id_here',
    authDomain: 'your_project_id_here.firebaseapp.com',
    storageBucket: 'your_project_id_here.firebasestorage.app',
    measurementId: 'your_measurement_id_here',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your_android_api_key_here',
    appId: 'your_android_app_id_here',
    messagingSenderId: 'your_sender_id_here',
    projectId: 'your_project_id_here',
    storageBucket: 'your_project_id_here.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your_ios_api_key_here',
    appId: 'your_ios_app_id_here',
    messagingSenderId: 'your_sender_id_here',
    projectId: 'your_project_id_here',
    storageBucket: 'your_project_id_here.firebasestorage.app',
    iosBundleId: 'your_bundle_id_here',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your_macos_api_key_here',
    appId: 'your_macos_app_id_here',
    messagingSenderId: 'your_sender_id_here',
    projectId: 'your_project_id_here',
    storageBucket: 'your_project_id_here.firebasestorage.app',
    iosBundleId: 'your_bundle_id_here',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your_windows_api_key_here',
    appId: 'your_windows_app_id_here',
    messagingSenderId: 'your_sender_id_here',
    projectId: 'your_project_id_here',
    authDomain: 'your_project_id_here.firebaseapp.com',
    storageBucket: 'your_project_id_here.firebasestorage.app',
    measurementId: 'your_windows_measurement_id_here',
  );
}